// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Instances = require("./Instances.bs.js");

var x = 42;

var y = Curry._2(Instances.$$Option[/* Functor */0][/* map */0], (function (a) {
        return (a << 1);
      }), x);

console.log(x);

console.log(y);

exports.x = x;
exports.y = y;
/* y Not a pure module */
